// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkQ9rj_eMDx-b13bvBx-sNp3nupjRD0E',
    appId: '1:37136378230:web:7c0090de4434bda91bb257',
    messagingSenderId: '37136378230',
    projectId: 'superwizor-staging',
    authDomain: 'superwizor-staging.firebaseapp.com',
    storageBucket: 'superwizor-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuzQs3FnU8J7saKXXCUXH7kV7pfRSiRE',
    appId: '1:37136378230:android:fb37ecc9ffbf73e61bb257',
    messagingSenderId: '37136378230',
    projectId: 'superwizor-staging',
    storageBucket: 'superwizor-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdnAx3_8v0lwLyuyHWDG_hcavm1NLWFT4',
    appId: '1:37136378230:ios:c9df576a2e815e531bb257',
    messagingSenderId: '37136378230',
    projectId: 'superwizor-staging',
    storageBucket: 'superwizor-staging.firebasestorage.app',
    iosBundleId: 'ai.superwizor.superwizor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdnAx3_8v0lwLyuyHWDG_hcavm1NLWFT4',
    appId: '1:37136378230:ios:c9df576a2e815e531bb257',
    messagingSenderId: '37136378230',
    projectId: 'superwizor-staging',
    storageBucket: 'superwizor-staging.firebasestorage.app',
    iosBundleId: 'ai.superwizor.superwizor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkQ9rj_eMDx-b13bvBx-sNp3nupjRD0E',
    appId: '1:37136378230:web:b2b83b5d5900a8f41bb257',
    messagingSenderId: '37136378230',
    projectId: 'superwizor-staging',
    authDomain: 'superwizor-staging.firebaseapp.com',
    storageBucket: 'superwizor-staging.firebasestorage.app',
  );
}
