steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/superwizor-staging/services/identity-svc:v0.1.0', '-f', 'services/identity-svc/Dockerfile', '.']
images:
- 'europe-central2-docker.pkg.dev/superwizor-staging/services/identity-svc:v0.1.0'
