// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTAFc7rLVQsPU--8uWl9x_2NV2mlz6zk',
    appId: '1:895484488067:web:b4b01d066927712cfc6eb6',
    messagingSenderId: '895484488067',
    projectId: 'superwizor-app-core',
    authDomain: 'superwizor-app-core.firebaseapp.com',
    storageBucket: 'superwizor-app-core.firebasestorage.app',
    measurementId: 'G-4HKX4E1ZVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3k3ZDXLK4rpOohelf_gucddz5YFgqw4Y',
    appId: '1:895484488067:android:92dc134b10b7ee94fc6eb6',
    messagingSenderId: '895484488067',
    projectId: 'superwizor-app-core',
    storageBucket: 'superwizor-app-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2dd2XyY3S1SHvcRURKr0Me2ik8FoWD0',
    appId: '1:895484488067:ios:b97f449f61686522fc6eb6',
    messagingSenderId: '895484488067',
    projectId: 'superwizor-app-core',
    storageBucket: 'superwizor-app-core.firebasestorage.app',
    iosBundleId: 'com.superwizor.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2dd2XyY3S1SHvcRURKr0Me2ik8FoWD0',
    appId: '1:895484488067:ios:b97f449f61686522fc6eb6',
    messagingSenderId: '895484488067',
    projectId: 'superwizor-app-core',
    storageBucket: 'superwizor-app-core.firebasestorage.app',
    iosBundleId: 'com.superwizor.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTAFc7rLVQsPU--8uWl9x_2NV2mlz6zk',
    appId: '1:895484488067:web:44a9f855959ccd3dfc6eb6',
    messagingSenderId: '895484488067',
    projectId: 'superwizor-app-core',
    authDomain: 'superwizor-app-core.firebaseapp.com',
    storageBucket: 'superwizor-app-core.firebasestorage.app',
    measurementId: 'G-YKWXT5MDV9',
  );
}
